spring:
  main:
    allow-circular-references: true # 允许循环依赖
  application:
    name: nacos-discovery-provider
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: geminis:8848
        namespace: acf7aadc-1f86-4dfb-9c55-e33b1ff70c62 # 需要与nacosServer的命名空间ID一致
      username: nacos
      password: nacos
# server
server:
  port: 9100